package mx.com.satoritech.creditaco.navigation

object Screens {
    const val WELCOME = "WELCOME"

    const val LOGIN_SCREEN = "LOGIN_SCREEN"

    const val REGISTRATION_SCREEN = "REGISTRATION_SCREEN"

    const val HOME_SCREEN = "HOME_SCREEN"

    const val PROFILE_SCREEN = "PROFILE_SCREEN"

    const val EDIT_PROFILE_SCREEN = "EDIT_PROFILE_SCREEN"

    const val GAMES_SCREEN = "GAMES_SCREEN"

    const val GAME_DETAILS_SCREEN = "GAME_DETAILS_SCREEN"

    const val GENRES_SCREEN = "GENRES_SCREEN"

    const val GENRES_DETAILS_SCREEN = "GENRES_DETAILS_SCREEN"

    const val PLATFORMS_SCREEN = "PLATFORMS_SCREEN"

    const val PLATFORMS_DETAILS_SCREEN = "PLATFORMS_DETAILS_SCREEN"

    const val FAVORITE_GAMES_SCREEN = "FAVORITE_GAMES_SCREEN"

}

